Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  IgnoredPatterns: ['(\A|\s)#']

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
