language: ruby

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - docker-compose build

before_script:
  - docker-compose run --rm --no-deps web echo 'Gems now pre-installed.'
  - docker-compose up -d
  - docker ps

notifications:
  webhooks: https://coveralls.io/webhook

script:
  - docker-compose exec web rubocop
  - docker-compose exec web rspec

after_script:
  - docker-compose exec web coveralls:push
  - docker-compose down
