language: ruby
rvm:
- 2.7.0
cache: bundler
bundler_args: --jobs 3 --retry 3
before_install:
  - travis_retry gem update --system --no-document
  - travis_retry gem install bundler
notifications:
  webhooks: https://coveralls.io/webhook
jobs:
  include:
    - stage: 'Code scanning'
      name: 'Codestyle checking'
      script:
        - bundle exec rubocop
    - stage: 'Testing'
      name: 'Testing'
      services:
        - postgresql
      before_script:
        - bundle exec rake db:setup
      script:
        - bundle exec rake rspec
      after_script:
        - bundle exec rake coveralls:push
